default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: creekstone_dev

test: &test
  <<: *default
  database: creekstone_test

production:
  <<: *default
  database: creekstone_prod

cucumber:
  <<: *test